### ISSUE TITLE
TF-Update The Stack with new languages and licenses

### ISSUE THREAD

**Issue by lvwerra** [bigcode-project/bigcode-dataset#10]
The first version of The Stack included those weak copyleft licenses and we should exclude them.

**Comment by pombredanne** [comment]
FWIW, you may want to consider a more up-to-date license detection engine such as scancode-toolkit (that I maintain) as you may otherwise have several undetected licenses.

**Comment by harm-devries** [comment]
@pombredanne thanks! I didn't know about scancode-toolkit. We'll use that in the future :)

**Comment by pombredanne** [comment]
@harm-devries I am hopelessly biased of course, but this is considered not too shabby. Used by SWH in https://annex.softwareheritage.org/public/dataset/license-blobs/ (which likely may be something you would fancy), tern, ORT and many more. Ping me if you need help!

**Comment by pombredanne** [comment]
@lvwerra since you closed this can you elaborate what has been done exactly?

**Comment by lvwerra** [comment]
For the current iteration we used the same license information as for the original stack but extended it to ~150 permissive licenses and added roughly ~300 programming languages. There will likely be more updates to The Stacks where we can update the license detector.
