### ISSUE TITLE
Dataset filtering based on content

### ISSUE THREAD

**Issue by lvwerra** [bigcode-project/bigcode-dataset#14]
Most code models following Codex used some content based filtering (e.g. max/mean line length of file, fraction of alphanumeric characters). These work well for Python but can fail for other langugages as HTML. We need to gather good filters for each language, especially the high volume languages such as HTML, Java, JavaScript, Python, C, C++ etc.

**Comment by RaymondLi0** [comment]
Another interesting approach that was mentioned was to use the tokenizer to remove files that are outliers in term of character-to-token ratio
