### ISSUE TITLE
Run language detection GitHub issues

### ISSUE THREAD

**Issue by lvwerra** [bigcode-project/bigcode-dataset#30]
We need to detect and filter languages on GitHub issues. For example the language detector from `fasttext` could be used for this

**Comment by loubnabnl** [comment]
There's some code to do natural language identification with `fasttext` on comments in code [here](https://github.com/bigcode-project/bigcode-analysis/tree/main/data_analysis/python_data_analysis/nl_language_identification) as a starting point. A subset of GitHub issues is also available [here](https://huggingface.co/datasets/bigcode/subset-github-issues) (private dataset in BigCode org)

**Comment by Muhtasham** [comment]
Hi there, I would like to contribute to this :)

**Comment by loubnabnl** [comment]
Great! Let us know if you need any help

**Comment by Muhtasham** [comment]
@loubnabnl can you give more context where exactly the language detector needs to be added, in preprocessing or somewhere else

**Comment by loubnabnl** [comment]
Thanks for the analysis @Muhtasham , the language detector is needed to create a training dataset with english issues only, that we will apply quality filters to (not started if you're interested) + PII (in progress).

Maybe you can post a summary of the findings on slack ([#tf-issues](https://bigcode-workspace.slack.com/archives/C04LJP3M205/p1674725005440609) channel). I saw you only use title + description for the detection, we can probably also try adding comments to see if that changes the results.
