### ISSUE TITLE
EDA on full dataset

### ISSUE THREAD

**Issue by lvwerra** [bigcode-project/bigcode-dataset#5]
It would be great if we could do some exploratory data analysis on the full dataset:
- Language distribution
- File length
- Licence distribution
This would help a bit with the understanding of the dataset and the trade-offs in filtering.

**Comment by loubnabnl** [comment]
I can take on this when we have the license information in the dataset.

**Comment by harm-devries** [comment]
Ideas from 19.9 meeting:
- Tokenizer fertility for different programming languages (easy)
- Check how many files might contain PII (detected by regex)? (easy) 
- Investigate how many code files actually compile? (Python) (easy for python, hard for all languages)
- Distribution of natural language in Github corpus? (Only run on comments and docstrings) (easy for python, hard for all languages)

**Comment by loubnabnl** [comment]
I added the [code]( https://github.com/bigcode-project/bigcode-analysis/blob/main/data_analysis/nl_language_identification/README.md) to extract dosctrings/comments from Python code and detect the language. 
A quick analysis on 2000 samples from CodeParrot data shows that only 4% of the data is detected as non English and here’s the distribution 

<h3 align="center">
    <img width="360" height="300" src="https://user-images.githubusercontent.com/44069155/191994477-6246467b-eec7-4ae1-a14d-dd2262254762.png" /></a>
</h3>

[Notebook](https://github.com/bigcode-project/bigcode-analysis/blob/main/data_analysis/nl_language_identification/analysis.ipynb) for the analysis, BigCode dataset gives similar results

**Comment by loubnabnl** [comment]
I tried to compile 10k samples from BigCode python and only 0.24% didn't compile due to syntax errors. You can find the notebook here https://github.com/bigcode-project/bigcode-analysis/blob/main/data_analysis/notebooks/code_compilation.ipynb
