### ISSUE TITLE
Parse code dataset into AST

### ISSUE THREAD

**Issue by harm-devries** [bigcode-project/bigcode-dataset#6]

**Comment by harm-devries** [comment]
Interesting finding from the [PanGu paper](https://arxiv.org/abs/2207.11280). 

They are able to significantly improve HumanEval performance by fine-tuning on a "Code CLM" dataset that more closely resembles the text2code evaluation setup. Specifically, they parse the python dataset to an AST and then re-arrange the format of all functions (and classes) to <descr> docstring <python> code <eos>. 

This improves the performance from ~25% to ~34% for a 300M+ parameter model.

**Comment by harm-devries** [comment]
1. Parse python into AST, see https://github.com/tree-sitter/tree-sitter-python
2. Run it on full Python dataset (all license)
3. Filter all function/classes with docstrings and reformat into Code-CLm format

**Comment by bigximik** [comment]
Things done so far and TODO:
- tree_sitter changed to version 0.20.1
- python grammar updated to v0.20.0, parser changed to accommodate new version api
    - python parsing tests added
    - python parser recognises class and functions as empty even with docstrings now
    - NOTE: wile parsing python if there is error, indentation error, in the beginning of the definition, tree_sitter will return all the rest of the file as block for that definition
    - TODO: add support for decorators
- javascrip grammar updated to v0.19.0, parser changed for functions to accommodate new version api, also to support arrow notation
    - javascrip parsing tests added for functions,
    - TODO: add tests for classes, make changes to parse functions in classes if needed
- go grammar updated to v0.19.1,
    - TODO: change parser, add tests
- java grammar updated to v0.20.0,
    - TODO: change parser, add tests
- ruby grammar added at v0.19.0
    - TODO: change parser, add tests
- php grammar added at v0.19.0,
    - TODO: change parser, add tests
- TODO: add extended tokeniser which preserves separation syntax event it is like indentation in python
- TODO: add human language classification in docstrings, eng/ not eng at a minimum
- TODO: add functionality to return definition text without documentation or comments
- TODO: add option to retrieve all comments in a function as extended docstring

https://github.com/bigcode-project/function_parser/blob/main/CHANGELOG.md
