### ISSUE TITLE
Create near-dedup dataset for all programming languages

### ISSUE THREAD

**Issue by harm-devries** [bigcode-project/bigcode-dataset#8]

**Comment by harm-devries** [comment]
- Do near-deduplication for all-license and safe-license
- Update dataset histogram here: https://docs.google.com/spreadsheets/d/1UI--YM7bi6nIqFIHFWpeLScBljnb8i7Y6F1RdbbuM1w/edit?usp=sharing

**Comment by lvwerra** [comment]
Assuming there is not too much overlap between languages this could probably be done per language. So split the dataset per language, dedup, and then combine the languages. This would reduce the memory/compute burden of deduplication.

**Comment by harm-devries** [comment]
Can we propose a dataset format for release on the hub? @RaymondLi0 @loubnabnl

**Comment by RaymondLi0** [comment]
Here is the proposed list of columns:
- `content`: content of the file
- `repository`: name of the repository. If a file appears in several repositories that satisfy our license criterion, it will only show the first in alphabetical order.
- `licenses`: list of licenses that were detected in the repository. They will all be "safe licenses"
- `path`: relative path in the repository
- `size`: size of the uncompressed file
- `language`
- other stats on the content of the file: `avg_line_length`, `max_line_length`, `alphanum_fraction`

**Comment by RaymondLi0** [comment]
A complimentary dataset will join file ids to all the repositories, paths and licenses that were originally in the dataset

**Comment by RaymondLi0** [comment]
The unfiltered dataset is being uploaded here: https://huggingface.co/datasets/bigcode/multi_safe_license_raw

Size and number of files per language:

![Image](https://user-images.githubusercontent.com/11444023/193626040-69d37c4a-459f-475e-bb03-8de94753e07e.png)

**Comment by veerumehta** [comment]
Is de-dup always the best strategy or could it lead to loss of useful info? it may cause novel implementation to be drowned out but wisdom of crowds is beneficial to track at times ...
